# Generated by Django 4.2.4 on 2023-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='порядковый номер')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'Образовательный модуль',
                'verbose_name_plural': 'Образовательные модули',
            },
        ),
    ]
