# Generated by Django 4.2.4 on 2023-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_modules', '0002_module_number_alter_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='порядковый номер'),
        ),
    ]
