# Generated by Django 4.2.4 on 2023-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_modules', '0003_alter_module_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='module',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='порядковый номер'),
        ),
    ]
