# Generated by Django 4.2.4 on 2023-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_modules', '0007_alter_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='здесь должно быть описание', max_length=15000, verbose_name='описание'),
        ),
    ]
